site: 1Aime7

url:
baseurl: "/"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: false
  projects:
    output: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: "minimal"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-sitemap


# Minify HTML
compress_html:
 clippings: []
 comments: ["<!-- ", " -->"]
 endings: []
 blanklines: false
 profile: false
 startings: []
